{% set version = "4.13.2" %}
{% set build_number = 0 %}

package:
  name: antlr-python-runtime-meta
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/a/antlr4-python3-runtime/antlr4_python3_runtime-{{ version }}.tar.gz
    sha256: 909b647e1d2fc2b70180ac586df3933e38919c85f98ccc656a96cd3f25ef3916
  - url: https://raw.githubusercontent.com/antlr/antlr4/{{ version }}/LICENSE.txt
    sha256: 3db1fb3ee79a4b4f9918fc4d0f6133bf18a3cf787f126cd22f8aa9b862281c0c

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "tests in outputs"

outputs:

  - name: antlr-python-runtime
    build:
      build_number: {{ build_number }}
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps --no-index -vv --no-build-isolation
      entry_points:
        - pygrun=antlr4._pygrun:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
    test:
      imports:
        - antlr4
        - antlr4.atn
        - antlr4.dfa
        - antlr4.error
        - antlr4.tree
        - antlr4.xpath
      commands:
        - pip check
        - pygrun -h
      requires:
        - pip

  - name: antlr4-python3-runtime
    build:
      build_number: {{ build_number }}
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.6
        - antlr-python-runtime {{ version }}.*
    test:
      imports:
        - antlr4

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: This is the Python runtime for ANTLR.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/python-target.md

extra:
  feedstock-name: antlr-python-runtime
  recipe-maintainers:
    - bollwyvl
