{% set version = "4.10" %}
{% set build_number = 0 %}

package:
  name: antlr-python-runtime-meta
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/a/antlr4-python3-runtime/antlr4-python3-runtime-{{ version }}.tar.gz
    sha256: 061a49bc72ae05a35d9b61c0ba0ac36c0397708819f02fbfb20a80e47d287a1b
    patches:
      - 0001-add-entry-point.patch
      - 0002-add-main-for-entry-point.patch

  - url: https://raw.githubusercontent.com/antlr/antlr4/{{ version }}/LICENSE.txt
    sha256: b1b379fcaf3219593a4c433feb1b35c780bed23fafaae440b1ae2771a9521e3a

build:
  number: {{ build_number }}
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - echo "tests in outputs"

outputs:

  - name: antlr-python-runtime
    build:
      build_number: {{ build_number }}
      noarch: python
      script:
        - {{ PYTHON }} -c "__import__('os').rename('bin/pygrun', 'src/antlr4/_pygrun.py')"
        - {{ PYTHON }} -m pip install . --no-deps --no-index -vv
      entry_points:
        - pygrun=antlr4._pygrun:main
    requirements:
      host:
        - pip
        - python >=3.6
      run:
        - python >=3.6
    test:
      imports:
        - antlr4
        - antlr4.atn
        - antlr4.dfa
        - antlr4.error
        - antlr4.tree
        - antlr4.xpath
      commands:
        - pip check
        - pygrun -h
      requires:
        - pip

  - name: antlr4-python3-runtime
    build:
      build_number: {{ build_number }}
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.6
        - antlr-python-runtime {{ version }}.*
    test:
      imports:
        - antlr4

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: This is the Python runtime for ANTLR.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/python-target.md

extra:
  feedstock-name: antlr-python-runtime
  recipe-maintainers:
    - bollwyvl
