{% set name = "antlr4-python2-runtime" %}  # [py2k]
{% set name = "antlr4-python3-runtime" %}  # [py3k]
{% set version = "4.8" %}

package:
  name: antlr-python-runtime
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f568d238e05e6a4a8f321731bfd96238a6e2fadcdb09b57445369746b120a17e  # [py2k]
    sha256: 15793f5d0512a372b4e7d2284058ad32ce7dd27126b105fb0b2245130445db33  # [py3k]

  - url: https://raw.githubusercontent.com/antlr/antlr4/{{ version }}/LICENSE.txt
    sha256: b1b379fcaf3219593a4c433feb1b35c780bed23fafaae440b1ae2771a9521e3a

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - antlr4
    - antlr4.atn
    - antlr4.dfa
    - antlr4.error
    - antlr4.tree
    - antlr4.xpath

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: This is the Python runtime for ANTLR.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/python-target.md

extra:
  recipe-maintainers:
    - bollwyvl
