{% set name = "antlr4-python3-runtime" %}
{% set version = "4.9.3" %}

package:
  name: antlr-python-runtime
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: f224469b4168294902bb1efa80a8bf7855f24c99aef99cbefc1bcd3cce77881b

  - url: https://raw.githubusercontent.com/antlr/antlr4/{{ version }}/LICENSE.txt
    sha256: b1b379fcaf3219593a4c433feb1b35c780bed23fafaae440b1ae2771a9521e3a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pip
  imports:
    - antlr4
    - antlr4.atn
    - antlr4.dfa
    - antlr4.error
    - antlr4.tree
    - antlr4.xpath
  commands:
    - pip check

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: This is the Python runtime for ANTLR.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/python-target.md

extra:
  recipe-maintainers:
    - bollwyvl
