appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: XpJIXH0dTlNX7YWG9o4XSC72DD1CrqWAoXv1roe1Dh0rSW6tAM7GXP5baZ+Sfvd0Lq4Gnj1RTYAB24P+Hq90yhOhHgYdvz1bg13DAgqjJwFXOSOIyKYs7pX3RKu2bKINKw3vKqdM779eK7HAn5F8QCuJcaxFnmTu6KMkKG+vH25xdL1Xe+JMTGYCUlbUTo+0GGvraSKSOgYKFtbRl4b6pYrIFbULDN9WiZGFHZ/qwO8TVY7K9bCppZnGw95Rrm9v3Rzo7WDB0NqoIqhw4+sJDOIgI58Kh+5oLZgxZF+HZHVOMXbMEtNZ91zLyGvgLkvdDKFFBSB1lY9u6FVoJIxIdLYZWG50Ahffoimsuke3ogq84Zv15saSWY8VU8WQ3jdl61Q2QO8RJaEmi6dGINztJHf+YAylU1gkVGj//ADK/gPVx8u+Sj8bgI5bOjljHs412oEQvRm1DXHXCl+Lw3PAqM+ee0Bbw63Vv0IvG1WXU69Ck/C1jPpmbJlgIMTVD+QHzRLo4c78ms5/jBD3wGY59yjwWL8QLKirVUt51TqBbvqHUCi3fMF+kXBpVxyhRQYlLeyoNQazNk88HnYTDkWYQGY4Z5NK9bNF8NSJG6cmSjhPSyvCs6Sr6YyY7meX+/W+PzlHM84GVcFqtzgAreivzeeRWs+6exKdMZb9mms96Ms=}
provider:
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
